### lista todos los servicios
GET http://localhost:3001/api/servicio

### lista el detalle de un servicio por su id
GET  http://localhost:3001/api/servicio/3

### lista todos los servicios de un profesional
GET http://localhost:3001/api/serviciosForProfesional/1

### registra un servicio
POST http://localhost:3001/api/servicio
Content-Type: application/json

{
    "nombre":"pruebaback",
    "descripcion":"curso en linea de ingles de prueba",
    "tipo":3,
    "precio":1.1,
    "profesional":3,
    "foto":"urlpruebaback"
}

### editar un servicio por su id
PUT http://localhost:3001/api/servicio/1
Content-Type: application/json

{
    "nombre":"Terapia Reumatologíca",
    "descripcion":"La Fisioterapia Traumatológica es una especialidad indicada para el tratamiento de las lesiones del sistema musculo esquelético, óseo y ligamentoso de las diferentes partes del cuerpo humano.",
    "precio":1,
    "descuento":20
}
