### agrega un comentario
POST http://localhost:3001/api/valoracion
Content-Type: application/json

{
    "comentario":"prueba back",
    "idServicio":1,
    "idCliente":1
}

### lista todas los comentarios de un servicio por id
GET http://localhost:3001/api/valoraciones/3